name: flutter_internet_speed_test
description: A Flutter plugin to test internet download and upload speed.
version: 1.4.0
homepage: https://github.com/shaz-tech/flutter_internet_speed_test

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  #tuple: ^2.0.0
  tuple_dart: ^1.4.2
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.shaz.plugin.fist.flutter_internet_speed_test
        pluginClass: FlutterInternetSpeedTestPlugin
      ios:
        pluginClass: FlutterInternetSpeedTestPlugin
